#!/bin/bash

#-e -- включить поддержку вывода Escape последовательностей;
echo -e "======================== Start ========================\n"

mkdir lab0
cd lab0

# -p или --parents - создаёт все директории, которые указыны внутри пути
#если уже какая-то дирекория существуте, то придупреждений нет 
mkdir -p buneary4
mkdir -p buneary4/arcanine
mkdir -p meditite1
mkdir -p meditite1/drowzee
mkdir -p prinplup1
mkdir -p prinplup1/hitmontop 
mkdir -p prinplup1/krokorok  
mkdir -p prinplup1/mantyke 
mkdir -p prinplup1/rhyperior 

# touch — команда Unix, предназначенная для установки времени последнего изменения файла или доступа в текущее время.
# Также используется для создания пустых файлов.
touch buneary4/scizor
touch buneary4/shelgon
touch kakuna6
touch lileep6
touch meditite1/mankey
touch meditite1/primeape
touch prinplup1/whimsicott
touch prinplup1/staraptor
touch sceptile3

echo -e "Живет Grassland Mountain" > buneary4/scizor
echo -e "Возможности Overland=7\nSurface=5 Jump=2 Power=4 Intelligence=3" > buneary4/shelgon
echo -e "Ходы Bug Bite\nElectroweb Iron Defense String Shot Tackle" > kakuna6
echo -e "Тип покемона ROCK\nGRASS" > lileep6
echo -e "Тип диеты\nOmnivore" > meditite1/mankey
echo -e "Тип покемона FIGHTING\nNONE" > meditite1/primeape
echo -e "Ходы Cotton Spore# Covet Endeavor Giga Drain Growtht#\nHelping Hand Knock Off Leech Seed# Mega Drain# Seed Bomb Sleep Talk\nSnore Tail-wind Worry Seed" > prinplup1/whimsicott
echo -e "Тип покемона\tNORMAL\nFLYING" > prinplup1/staraptor
echo -e "Ходы Body Slam Bullet Seed Counter Double-Edge\nDragon Pulse Drain Punch Dynamicpunch Endeavor Focus Punch Frenzy\nPlant Fury Cutter Giga Drain Grass Pledge Iron Tail Low Kick Mega Kick\nMega Punch Mud-Slap Night Slash+ Outrage Rock Climb Secret Power Seed\nBomb Seismic Toss Sleep Talk Snore Swift Synthesis Thunderpunch Worry\nSeed" > sceptile3

#2 ЧАСТЬ
# chmod - команда которая задёт права для использования. [ugoa](u() - владелец, g(group) - группа владелец, o(other) - остальные, a(all) - все) +-=
# chmod -R -- рекурсивно задёт права всем внутри каталога, вкдючая сам каталог
chmod 363 buneary4
chmod 006 buneary4/scizor
chmod 060 buneary4/shelgon
chmod 764 buneary4/arcanine
chmod 624 kakuna6
chmod 624 lileep6
chmod 571 meditite1
chmod 363 meditite1/drowzee
chmod 400 meditite1/mankey
chmod 404 meditite1/primeape  
chmod 573 prinplup1
chmod 733 prinplup1/hitmontop
chmod 444 prinplup1/whimsicott
chmod 755 prinplup1/krokorok
chmod 307 prinplup1/mantyke
chmod 044 prinplup1/staraptor
chmod 771 prinplup1/rhyperior
chmod 444 sceptile3

# 3 ЧАСТЬ

#Команда выдаст ошибку т.к. у drowzee нет прав на чтение
#Выдаем необходимые права и убираем их после копирования 
chmod u+r meditite1/drowzee
cp -r meditite1  prinplup1/rhyperior
chmod u-r meditite1/drowzee

cp lileep6 buneary4/shelgonlileep

#Команда выдаст ошибку т.к. у staraptor нет прав на чтение
#Выдаем необходимые права и убираем их после выполнения задания
chmod u+r prinplup1/staraptor
cat prinplup1/staraptor meditite1/mankey > lileep6_91
chmod u-r prinplup1/staraptor

#Команда выдаст ошибку т.к. у meditite1 нет прав на запись
#Выдаем необходимые права и убираем их после создания ссылки
chmod u+w meditite1
ln -s lileep6 meditite1/primeapelileep
chmod u-w meditite1

ln -s buneary4 Copy_46

cp lileep6 buneary4/arcanine

#Команда выдаст ошибку т.к. у meditite1 нет прав на запись
#Выдаем необходимые права и убираем их после создания ссылки
chmod u+w meditite1
ln kakuna6 meditite1/primeapekakuna
chmod u-w meditite1

# 4 ЧАСТЬ

# wc - анализирует содержимое файлов, -m(подсчёт символов)
# sort - сортирует то что ему вводят на поток ввода, -r(сортировка в обратном порядке)
# >> - поток вывода(для текстовых файлов), << - поток ввода, 2>> - поток ошибок (всё в допление уже записаному, >,<,2> - перезаписывает)
# | - поток ввода не для текстовых файлов

wc -m meditite1/mankey meditite1/primeape | sort -r 2> /tmp/myproblems  # -m -- количество символов в файле/файлах 
echo -e ''

#Команда выдаст ошибку т.к. у buneary4 нет прав на чтение
#Выдаем необходимые права и убираем их после фильтрации
chmod u+r buneary4
ls -Rl buneary4 | grep '^-' | sort -k7 # -R - рекурсивно выводит все файлы в дирекории
chmod u-r buneary4
echo -e ''

#Команда выдаст ошибку т.к. у buneary4, buneary4/scizor и buneary4/shelgon нет прав на чтение
#Выдаем необходимые права и убираем их после фильтрации
chmod u+r buneary4; chmod u+r buneary4/scizor; chmod u+r buneary4/shelgon
cat -n buneary4/scizor buneary4/shelgon meditite1/mankey meditite1/primeape prinplup1/whimsicott | grep -vi 'rry' 2>&1 #-v -- инверсивный поиск, -i -- игнорировать регистр
chmod u-r buneary4; chmod u-r buneary4/scizor; chmod u-r buneary4/shelgon
echo -e ''

ls -l meditite1 | sort -k1 | grep '^-' | sort -k8
echo -e ''

#Команда выдаст ошибку т.к. у buneary4, meditite1/drowzee и prinplup1/mantyke нет прав на чтение
#Выдаем необходимые права и убираем их после фильтрации 
chmod u+r buneary4; chmod u+r meditite1/drowzee; chmod u+r prinplup1/mantyke;
ls -Rl | grep '^-' | sort -r | head -3 2>> /tmp/myproblems
chmod u-r buneary4; chmod u-r meditite1/drowzee; chmod u-r prinplup1/mantyke;
echo -e ''

#Команда выдаст ошибку т.к. у buneary4, meditite1/drowzee и prinplup1/mantyke нет прав на чтение
#Выдаем необходимые права и убираем их после фильтрации
chmod u+r buneary4; chmod u+r meditite1/drowzee; chmod u+r prinplup1/mantyke;
ls -Rl | grep '^-' | grep 'le' | sort 2>/dev/null
chmod u-r buneary4; chmod u-r meditite1/drowzee; chmod u-r prinplup1/mantyke;

# 5 ЧАСТЬ

rm -rf sceptile3 # -r -- Удаление директорий и их содержимого; -f -- Игнорировать несуществующие файлы и аргументы

#Команда выдаст ошибку т.к. у prinplup1 нет прав на запись
#Выдаем необходимые права и убираем их после удаления
chmod u+w prinplup1
rm -rf prinplup1/staraptor
chmod u-w prinplup1

#Команда выдаст ошибку т.к. у meditite1 нет прав на запись
#Выдаем необходимые права и убираем их после удаления
chmod u+w meditite1
rm -rf meditite1/primeapelile*
chmod u-w meditite1

#Команда выдаст ошибку т.к. у meditite1 нет прав на запись
#Выдаем необходимые права и убираем их после удаления
chmod u+w meditite1
rm -rf meditite1/primeapekaku*
chmod u-w meditite1

#Команда выдаст ошибку т.к. у meditite1 нет прав на запись и исполнение, а у meditite1/deowzee нет прав на чтение 
#Выдаем необходимые права и удалим директорию
chmod  u+w+x meditite1; chmod u+r meditite1/drowzee
rm -rf meditite1

#Команда выдаст ошибку т.к. у prinplup1 нет прав на запись
#Выдаем необходимые права и убираем их после удаления
chmod u+w prinplup1
rm -rf prinplup1/hitmontop
chmod u-w prinplup1

echo -e "\n======================== Finish ========================"
