
DROP TABLE ID_SOUL_ID_ACTIONS;
DROP TABLE ACTIONS;
DROP TABLE SOUL;
DROP TABLE ENITY;
DROP TABLE RACE;
DROP TABLE BODY;
DROP TABLE LEVEL;
DROP TABLE WORLD;

DROP TYPE BODY_TYPE;
DROP TYPE EVALUATION_TYPE;
DROP TYPE WORLD_TYPE;
DROP TYPE RACE_TYPE;

DROP DOMAIN POSSITIVE_INT;
